logging:
  level:
    ROOT: DEBUG

resilience4j:
  ratelimiter:
    instances:
      review-service:
        limitRefreshPeriod: 10s
        limitForPeriod: 4
        timeoutDuration: 5s
      calculator-service:
        limitRefreshPeriod: 20s
        limitForPeriod: 5
        timeoutDuration: 5s
  circuitbreaker:
    instances:
      review-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 4
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException

sec01:
  product.service: "http://localhost:6060/sec01/product"
  review.service: "http://localhost:6060/sec01/review"
  promotion.service: "http://localhost:6060/sec01/promotion"

sec02:
  delta.service: "http://localhost:6060/sec02/delta/"
  frontier.service: "http://localhost:6060/sec02/frontier"
  jetblue.service: "http://localhost:6060/sec02/jetblue"

sec03:
  product.service: "http://localhost:6060/sec03/product"
  user.service: "http://localhost:6060/sec03/user"
  shipping.service: "http://localhost:6060/sec03/shipping"
  inventory.service: "http://localhost:6060/sec03/inventory"

sec04:
  product.service: "http://localhost:6060/sec04/product"
  user.service: "http://localhost:6060/sec04/user"
  shipping.service: "http://localhost:6060/sec04/shipping"
  inventory.service: "http://localhost:6060/sec04/inventory"

sec05:
  car.service: "http://localhost:6060/sec05/car/reserve"
  room.service: "http://localhost:6060/sec05/room/reserve"

sec06:
  product.service: "http://localhost:6060/sec06/product"
  review.service: "http://localhost:6060/sec06/review"

sec07:
  product.service: "http://localhost:6060/sec07/product"
  review.service: "http://localhost:6060/sec07/review"

sec08:
  product.service: "http://localhost:6060/sec08/product"
  review.service: "http://localhost:6060/sec08/review"

sec09:
  product.service: "http://localhost:6060/sec09/product"
  review.service: "http://localhost:6060/sec09/review"